projects:

  Project One:
    services:
      - label: Auth Service
        dependencies:
          - Users Service
        docker_compose_file_path: /Users/mohammad/Documents/projects/goworkspace/src/dcli-other-projects/project-one/auth-service/docker-compose.yaml
      - label: Users Service
        docker_compose_file_path: /Users/mohammad/Documents/projects/goworkspace/src/dcli-other-projects/project-one/users-service/docker-compose.yaml
      - label: Catalogue Service
        docker_compose_file_path: /Users/mohammad/Documents/projects/goworkspace/src/dcli-other-projects/project-one/catalogue-service/docker-compose.yaml
    common:
      docker_compose_file_path: /Users/mohammad/Documents/projects/goworkspace/src/dcli-other-projects/project-one/common-services/docker-compose.yaml
